package com.ioabsoftware.gameraven.networking;

public enum NetDesc {
    UNSPECIFIED, MODHIST, FRIENDS, FOLLOWING, FOLLOWERS,
    VERIFY_ACCOUNT_S1, VERIFY_ACCOUNT_S2,
    LOGIN_S1, LOGIN_S2,
    // GFAQS_SETTINGS,
    BOARDS_EXPLORE, BOARDS_FAVORITE, BOARD, BOARD_UPDATE_FILTER,
    GAME_SEARCH, AMP_LIST, TRACKED_TOPICS, TOPIC, MESSAGE_DETAIL, USER_DETAIL,
    PM_INBOX, PM_OUTBOX, PM_INBOX_DETAIL, PM_OUTBOX_DETAIL, PM_SEND_S1, PM_SEND_S2,
    TOPIC_CLOSE, TOPIC_UPDATE_FLAIR, TOPIC_POLL_VOTE,
    USER_TAG,
    MSG_POST, MSG_EDIT, MSG_DELETE, MSG_REPORT_START, MSG_REPORT_SUBMIT,
    TOPIC_POST,
    NOTIFS_PAGE, NOTIFS_CLEAR,
    MENTIONS_PAGE
}
